a.c
function chgMainMap(guNum)
function inputArea(val)
Referenced by searchHospitalInfo1.
function add_row(a, b, c, d, e, f, g, h, i, j)
Referenced by searchHospitalInfo1.
function delete_row()
Referenced by searchHospitalInfo1.
function searchHospitalInfo1(area)