hospital_doxygen.c
function chgMainMap(guNum)
change the photo of seoul mapp
if you click the map of seoul, the photo of seoul change to represent your area. number of photo. each number is matched each photo of seoul map.
function inputArea(val)
when you click the map of seoul, the area info box change synchronously. area name selected from map.
Referenced by searchHospitalInfo1.
function add_row(a, b, c, d, e, f, g, h, i, j)
make the table to show the hospital information.
the hospital information is shown at the info table. The hospital information is selected and displayed by the options you choose. each option value for select the hospital information.
Referenced by searchHospitalInfo1.
function delete_row()
delete all rows of table.
To show new hospital informations, Delete the existing information in the table and display the required information in the table. no parameter.
Referenced by searchHospitalInfo1.
function searchHospitalInfo1(area)
search the hospital information you want.
you can choose various options to select the hospital information. Hospital information is selected and displayed by the options you choose. You can simply check the hospital information you want through this information. The area name of the hospital you want to get.
References add_row, area, delete_row, inputArea, ref.