reservation_doxygen.c
var reservationNum
Referenced by reserve.
var adminId
var today
date min
setTimeout(function(){ firebase.auth().onAuthStateChanged(function(user){ if(user){ var ref=firebase.database().ref("User/Admin/");ref.on("value", function(snapshot) { snapshot.forEach(function(data) { if(data.val().email==firebase.auth().currentUser.email){ document.getElementById("name").value=data.val().username;document.getElementById("phone").value=data.val().phone_num;} });});ref=firebase.database().ref('User/Member/');ref.on("value", function(snapshot) { snapshot.forEach(function(data) { if(data.val().email==firebase.auth().currentUser.email){ document.getElementById("name").value=data.val().username;document.getElementById("phone").value=data.val().phone_num;} });});} });}, 2000)
Part of call the user information.
Access the user's personal information database using the user's email information,get his name and phone number, and put it in the reservation form. 'name' is the id of the column where the user's name is entered in the html file. 'phone' is the id of the column where the user's phone is entered in the html file.
References ref.
Referenced by aut_modify, aut_signUp, log, login, logout, mem_modify, mem_signUp.
function categoryChange1(e)
Change the option of hospital selection when selecting a region.
When a region is selected, access the hospital_info in the DB and find the hospitals corresponding to the selected area and put them all in the hospital self option. 'Hospital' is the id of the select space where users select the hospital to reserve within the html file.
References ref.
function dateSelected(e)
When selecting a date, the free time on the selected date at the hospital is added to the time option.
When selecting a date, the hospital receives the hospital's business hours information first and the information scheduled for that date. When the work is finished, add the time option when the appointment time is empty during the hospital reservation time. 'Hospital' is the id of the select space where users select the hospital to reserve within the html file. 'area' is the id of the select space where users select the area to reserve within the html file. 'date' is the id of the select space where users select the date to reserve within the html file. 'time' is the id of the select space where users select the time to reserve within the html file. open,close, openH, openM is the infirmation that hospital open time and close time
References area, ref.
function categoryChange2(e)
Code for displaying hospital information when choosing a hospital.
When selecting a hospital, the hospital information is received from the DB and the hospital information is displayed. 'Hospital' is the id of the select space where users select the hospital to reserve within the html file.
References ref.
function reserve()
A function that stores reservation information in db.
Read the values in the table, send the reservation information to DB, and make a reservation. Each variable means the id of the reservation table and the variable that stores it.
References area, cancel, date, reservationNum.